version: '1.0'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - node_modules_front:/frontend/node_modules
    networks:
      - app
    depends_on:
      - backend
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
      - node_modules_api:/api/node_modules
    networks:
      - app
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: 'apidb'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app
volumes:
  node_modules_api:
  node_modules_front:
networks:
  app:
    driver: bridge